### ISSUE TITLE
Wrong Path separator

### ISSUE THREAD

**Issue by Toby222** [emipa606/PawnEducation#3]
The path for the config file is hard-coded with `\` in the path [here](https://github.com/emipa606/PawnEducation/blob/e5062abf6f7e11019eeb4acb26b8a9fde55e30b7/Source/RimWorld_PawnEducation/ModSettings.cs#L113) and [here](https://github.com/emipa606/PawnEducation/blob/e5062abf6f7e11019eeb4acb26b8a9fde55e30b7/Source/RimWorld_PawnEducation/ModSettings.cs#L140), which causes it to be saved as a file named `Config\PawnEducation.config` as opposed to a file `PawnEducation.config` in a folder called `Config` on systems not using `\` as a separator
(namely Linux (including SteamOS))
Instead, [Path.PathSeparator](https://learn.microsoft.com/en-us/dotnet/api/system.io.path.pathseparator?view=netframework-4.7.2) should be used

**Comment by emipa606** [comment]
Should work better now, thanks for the report!
